/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        background: "#0E2A47",
        surface: "#103053",
        "surface-dim": "#08203B",
        "surface-bright": "#1B3D62",
        "surface-variant": "#1B3D62",
        "surface-container-lowest": "#061A30",
        "surface-container-low": "#0C2745",
        "surface-container": "#122F4F",
        "surface-container-high": "#1B3A5C",
        "surface-container-highest": "#244468",
        "on-background": "#F5E8D8",
        "on-surface": "#F5E8D8",
        "on-surface-variant": "#A6B5C7",
        "inverse-on-surface": "#0E2A47",
        "inverse-surface": "#F5E8D8",
        outline: "#5C7A95",
        "outline-variant": "#2A4665",
        primary: "#F0A091",
        "primary-fixed": "#F8C2B5",
        "primary-fixed-dim": "#F0A091",
        "primary-container": "#F0A091",
        "on-primary": "#F5E8D8",
        "on-primary-fixed": "#3A1410",
        "on-primary-fixed-variant": "#5C2218",
        "on-primary-container": "#3A1410",
        "inverse-primary": "#C77A6E",
        "surface-tint": "#F0A091",
        secondary: "#F5E8D8",
        "secondary-container": "#1B3D62",
        "on-secondary": "#0E2A47",
        "on-secondary-container": "#F5E8D8",
        "secondary-fixed": "#F5E8D8",
        "secondary-fixed-dim": "#F5E8D8",
        "on-secondary-fixed": "#0E2A47",
        "on-secondary-fixed-variant": "#1B3D62",
        tertiary: "#F5E8D8",
        "tertiary-container": "#1B3D62",
        "on-tertiary": "#0E2A47",
        "on-tertiary-container": "#F5E8D8",
        "tertiary-fixed": "#FBE7E0",
        "tertiary-fixed-dim": "#F0A091",
        "on-tertiary-fixed": "#3A1410",
        "on-tertiary-fixed-variant": "#5C2218",
        error: "#FFB4AB",
        "error-container": "#93000A",
        "on-error": "#690005",
        "on-error-container": "#FFDAD6",
      },
      fontFamily: {
        headline: ["Epilogue Variable", "Epilogue", "sans-serif"],
        body: ["Inter Variable", "Inter", "sans-serif"],
        label: ["Space Grotesk Variable", "Space Grotesk", "sans-serif"],
        display: ["Epilogue Variable", "Epilogue", "sans-serif"],
        data: ["Berkeley Mono", "monospace"],
        "mono-premium": ["JetBrains Mono Variable", "JetBrains Mono", "monospace"],
        editorial: ["Montserrat Variable", "Montserrat", "sans-serif"],
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      animation: {
        iridescent: "iridescent 8s linear infinite",
        "pulse-glow": "pulse-glow 3s ease-in-out infinite",
        scan: "scan 3s ease-in-out infinite",
        ticker: "ticker 28s linear infinite",
        "hue-rotate": "hue-rotate 20s linear infinite",
        "loading-bar": "loading-bar 1.5s ease-in-out infinite",
      },
      keyframes: {
        iridescent: {
          "0%, 100%": { "background-position": "0% 50%" },
          "50%": { "background-position": "100% 50%" },
        },
        "pulse-glow": {
          "0%, 100%": { box_shadow: "0 0 20px rgba(240,160,145,0.1), 0 0 0 1px rgba(240,160,145,0.2)" },
          "50%": { box_shadow: "0 0 40px rgba(240,160,145,0.35), 0 0 0 2px rgba(240,160,145,0.45)" },
        },
        scan: {
          "0%, 100%": { top: "20%", opacity: "0" },
          "10%, 90%": { opacity: "1" },
          "50%": { top: "80%" },
        },
        ticker: {
          "0%": { transform: "translateX(0)" },
          "100%": { transform: "translateX(-50%)" },
        },
        "hue-rotate": {
          from: { filter: "hue-rotate(0deg)" },
          to: { filter: "hue-rotate(360deg)" },
        },
        "loading-bar": {
          "0%": { transform: "translateX(-100%)" },
          "100%": { transform: "translateX(250%)" },
        },
      },
    },
  },
  plugins: [],
};
