/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-surface-variant": "#b9cbc1",
        "inverse-on-surface": "#222f52",
        "on-primary-fixed": "#002116",
        "on-background": "#dae2ff",
        "on-error-container": "#ffdad6",
        "on-secondary-fixed-variant": "#5516be",
        "on-secondary-fixed": "#23005c",
        "on-tertiary-fixed-variant": "#871d32",
        "error-container": "#93000a",
        outline: "#83958c",
        background: "#021133",
        "on-secondary-container": "#c4abff",
        "surface-container-low": "#0b1a3c",
        secondary: "#d0bcff",
        "primary-container": "#00ffc2",
        "outline-variant": "#3a4a43",
        "on-tertiary": "#67011d",
        error: "#ffb4ab",
        "on-primary": "#003828",
        "on-error": "#690005",
        "surface-container-highest": "#263456",
        "secondary-container": "#571bc1",
        "on-primary-fixed-variant": "#00513c",
        "on-tertiary-fixed": "#40000f",
        "secondary-fixed-dim": "#d0bcff",
        "inverse-primary": "#006c50",
        surface: "#021133",
        "tertiary-fixed-dim": "#ffb2b8",
        "on-primary-container": "#007255",
        "surface-bright": "#2b385b",
        "on-secondary": "#3c0091",
        "surface-dim": "#021133",
        "secondary-fixed": "#e9ddff",
        "primary-fixed-dim": "#00e1ab",
        primary: "#fbfffa",
        "on-surface": "#dae2ff",
        "inverse-surface": "#dae2ff",
        "tertiary-container": "#ffd8da",
        "surface-container-lowest": "#000c2c",
        "surface-container-high": "#1b294b",
        tertiary: "#fffdff",
        "surface-variant": "#263456",
        "tertiary-fixed": "#ffdadb",
        "surface-tint": "#00e1ab",
        "on-tertiary-container": "#ae3b4d",
        "surface-container": "#0f1e40",
        "primary-fixed": "#36ffc4",
      },
      fontFamily: {
        headline: ["Epilogue Variable", "Epilogue", "sans-serif"],
        body: ["Inter Variable", "Inter", "sans-serif"],
        label: ["Space Grotesk Variable", "Space Grotesk", "sans-serif"],
        display: ["Epilogue Variable", "Epilogue", "sans-serif"],
        data: ["Berkeley Mono", "monospace"],
        "mono-premium": ["JetBrains Mono Variable", "JetBrains Mono", "monospace"],
        editorial: ["Montserrat Variable", "Montserrat", "sans-serif"],
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      animation: {
        iridescent: "iridescent 8s linear infinite",
        "pulse-glow": "pulse-glow 3s ease-in-out infinite",
        scan: "scan 3s ease-in-out infinite",
        ticker: "ticker 28s linear infinite",
        "hue-rotate": "hue-rotate 20s linear infinite",
        "loading-bar": "loading-bar 1.5s ease-in-out infinite",
      },
      keyframes: {
        iridescent: {
          "0%, 100%": { "background-position": "0% 50%" },
          "50%": { "background-position": "100% 50%" },
        },
        "pulse-glow": {
          "0%, 100%": { box_shadow: "0 0 20px rgba(0,255,194,0.1), 0 0 0 1px rgba(0,255,194,0.2)" },
          "50%": { box_shadow: "0 0 40px rgba(0,255,194,0.4), 0 0 0 2px rgba(0,255,194,0.5)" },
        },
        scan: {
          "0%, 100%": { top: "20%", opacity: "0" },
          "10%, 90%": { opacity: "1" },
          "50%": { top: "80%" },
        },
        ticker: {
          "0%": { transform: "translateX(0)" },
          "100%": { transform: "translateX(-50%)" },
        },
        "hue-rotate": {
          from: { filter: "hue-rotate(0deg)" },
          to: { filter: "hue-rotate(360deg)" },
        },
        "loading-bar": {
          "0%": { transform: "translateX(-100%)" },
          "100%": { transform: "translateX(250%)" },
        },
      },
    },
  },
  plugins: [],
};
